<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_producto extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'producto_id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'nombre' => array(
				'type' => 'VARCHAR',
				'constraint' => 100,
			),
			'eliminado' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
		));

		$this->dbforge->add_key('producto_id', TRUE);

		$this->dbforge->create_table('producto', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('producto');
	}
}