<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_cel extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'cel_id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'desc' => array(
				'type' => 'VARCHAR',
				'constraint' => 50,
			),
		));

		$this->dbforge->add_key('cel_id', TRUE);

		$this->dbforge->create_table('cel', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('cel');
	}
}