<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_etiqueta extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'etiqueta_id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'producto_id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'tamano_id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'proveedor_id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'cantidad' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
		));

		$this->dbforge->add_key('etiqueta_id', TRUE);

		$this->dbforge->create_table('etiqueta', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('etiqueta');
	}
}