<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_proveedor extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'proveedor_id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'nombreProveedor' => array(
				'type' => 'VARCHAR',
				'constraint' => 50,
			),
		));

		$this->dbforge->add_key('proveedor_id', TRUE);

		$this->dbforge->create_table('proveedor', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('proveedor');
	}
}