<?php defined('BASEPATH') OR exit('No direct script access allowed');

/* This basic migration has been auto-generated by the Gas ORM */

class Migration_stock extends CI_Migration {

	public function up()
	{
		$this->dbforge->add_field(array(
			'stock_id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'producto_id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'tamano_id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'proveedor_id' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'usuario' => array(
				'type' => 'VARCHAR',
				'constraint' => 50,
			),
			'eliminado' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'cantidad' => array(
				'type' => 'INT',
				'constraint' => 11,
			),
			'fechaCreado' => array(
				'type' => 'DATETIME',
				'constraint' => 0,
			),
		));

		$this->dbforge->add_key('stock_id', TRUE);

		$this->dbforge->create_table('stock', TRUE);
	}

	public function down()
	{
		$this->dbforge->drop_table('stock');
	}
}