<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Cel extends ORM {
	
	public $primary_key = 'cel_id';

	function _init()
	{
		self::$fields = array(
			'cel_id' => ORM::field('auto[11]'),
			'desc' => ORM::field('char[50]'),
		);

	}
}