<?php namespace Model;

/* This basic model has been auto-generated by the Gas ORM */

use \Gas\Core;
use \Gas\ORM;

class Coords extends ORM {
	
	public $primary_key = 'coords_id';

	function _init()
	{
		self::$fields = array(
			'coords_id' => ORM::field('auto[11]'),
			'lat' => ORM::field('numeric'),
			'lon' => ORM::field('numeric'),
			'cel_id' => ORM::field('int[11]'),
		);

	}
}